title: RIGA Design Studio
description: Interior Design and Architectural Design Services
url: https://www.riga.mt
email: info@riga.mt
exclude: [".jekyll-cache", ".bundle", ".github", "Gemfile*", ".gitignore", "GitVersion.yml", ".git", "README.md", ".kodiak.toml", ".nojekyll", "LICENSE"]
include: [".well-known"]
ver: 0.0.0-local
livereload: true
host: 0.0.0.0
permalink: pretty
gtm-id: 
plugins:
  - jekyll-feed
  - jekyll-sitemap