source "https://rubygems.org"
gem "jekyll", "~> 4.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15.1"
  gem 'jekyll-sitemap'
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '~> 2.0'
  gem 'tzinfo-data', '~> 1.2021'
end

# Performance-booster for watching directories on Windows
gem "wdm", "= 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "webrick", "= 1.7.0"

gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'